services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=todolist
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - ./db:/docker-entrypoint-initdb.d